In [1]:
import pandas as pd


In [2]:
df=pd.read_csv('BAC.csv')

In [3]:
df.head()

Date       Open       High        Low      Close  Adj Close    Volume
0  2018-07-02  28.080000  28.280001  27.830000  28.280001  25.186296  52534300
1  2018-07-03  28.330000  28.430000  27.740000  27.780001  24.740997  40599000
2  2018-07-05  27.950001  28.080000  27.809999  27.920000  24.865677  44506800
3  2018-07-06  27.809999  28.150000  27.629999  28.030001  24.963646  39424900
4  2018-07-09  28.230000  29.090000  28.219999  29.049999  25.872059  61758900

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1258 non-null   object 
 1   Open       1258 non-null   float64
 2   High       1258 non-null   float64
 3   Low        1258 non-null   float64
 4   Close      1258 non-null   float64
 5   Adj Close  1258 non-null   float64
 6   Volume     1258 non-null   int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 68.9+ KB


In [5]:
df.fillna(method='ffill',inplace=True)

In [6]:
print(df.duplicated().sum())

0


In [7]:
df.drop_duplicates(inplace=True)

In [8]:
#df['Date']=pd.to_datetime(df['Date'])

In [9]:
df=df[['Date','Close']]

In [10]:
df.sort_values('Date',inplace=True)

In [11]:
df

Date      Close
0     2018-07-02  28.280001
1     2018-07-03  27.780001
2     2018-07-05  27.920000
3     2018-07-06  28.030001
4     2018-07-09  29.049999
...          ...        ...
1253  2023-06-26  28.090000
1254  2023-06-27  28.240000
1255  2023-06-28  28.070000
1256  2023-06-29  28.660000
1257  2023-06-30  28.690001

[1258 rows x 2 columns]

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [13]:
import numpy as np

In [14]:
X=df[['Date']].index.values.reshape(-1, 1).astype(np.float64)

In [15]:
print(X)

[[0.000e+00]
 [1.000e+00]
 [2.000e+00]
 ...
 [1.255e+03]
 [1.256e+03]
 [1.257e+03]]


In [18]:
y=df[['Close']].values.reshape(-1, 1).astype(np.float64)

In [19]:
print(y)

[[28.280001]
 [27.780001]
 [27.92    ]
 ...
 [28.07    ]
 [28.66    ]
 [28.690001]]


In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [21]:
model=LinearRegression()

In [22]:
model.fit(X_train,y_train)

LinearRegression()

In [23]:
y_pred=model.predict(X_test)

In [24]:
y_pred

array([[27.68277707],
       [31.59699185],
       [28.05898994],
       [35.52721569],
       [29.13159685],
       [27.78683595],
       [30.18019018],
       [31.73306884],
       [30.55640305],
       [32.2133406 ],
       [32.51751271],
       [33.67816944],
       [35.03093488],
       [31.33284238],
       [33.57411056],
       [36.51977731],
       [34.16644572],
       [36.92000377],
       [28.3231394 ],
       [36.87998112],
       [35.05494847],
       [28.63531604],
       [33.3099611 ],
       [31.58098279],
       [36.91199924],
       [29.33171008],
       [34.49463142],
       [34.790799  ],
       [31.26880615],
       [32.81368029],
       [28.93148362],
       [36.38370031],
       [36.7358996 ],
       [28.00295823],
       [34.41458613],
       [34.26250007],
       [34.18245478],
       [37.16814418],
       [31.49293297],
       [30.10814942],
       [29.79597278],
       [37.08009435],
       [35.78336062],
       [37.18415323],
       [36.82394942],
       [27

In [25]:
mse=metrics.mean_squared_error(y_test,y_pred)
print('MSE:',mse)

MSE: 35.87896224479698


In [26]:
r2=metrics.r2_score(y_test,y_pred)
print('R2 Score:',r2)

R2 Score: 0.16204392415211555


In [27]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [28]:
model=LinearRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [29]:
y_pred

array([[32.20637123],
       [28.59233956],
       [28.19951003],
       [28.29378912],
       [36.22894562],
       [31.13001832],
       [34.02910025],
       [36.00896108],
       [36.77890696],
       [35.94610836],
       [31.94710374],
       [36.04824403],
       [29.35442885],
       [32.1513751 ],
       [36.15037971],
       [30.58791357],
       [36.30751152],
       [33.8248289 ],
       [30.8943206 ],
       [35.48256951],
       [35.47471292],
       [31.05930901],
       [29.51156066],
       [33.76983276],
       [36.10324017],
       [33.53413504],
       [32.45778213],
       [29.83368087],
       [33.02345666],
       [28.13665731],
       [36.04038744],
       [30.36792904],
       [36.71605423],
       [34.87761204],
       [31.15358809],
       [31.54641762],
       [30.21865381],
       [30.12437473],
       [31.44428195],
       [29.33871567],
       [37.36815125],
       [32.74061939],
       [35.22330202],
       [28.76518455],
       [34.22551502],
       [34

In [30]:
mse=metrics.mean_squared_error(y_test,y_pred)
print('MSE:',mse)

MSE: 32.15349491630418


In [31]:
r2=metrics.r2_score(y_test,y_pred)
print('R2 Score:',r2)

R2 Score: 0.19306309323404092


In [33]:
y_pred.shape

(252, 1)